import {randomUUID} from 'node:crypto';
import {expect,it,vi} from 'vitest';
import {ProductionPilotReadSession} from '../../apps/api/src/production-pilot-read-session.js';
const scope={environment:'production',partnerId:'2010476',shopId:'1423724897',connectionRevision:1} as const;
const manifestSha256='a'.repeat(64);
function fixture(){let now=Date.parse('2026-09-15T10:00:00Z');const session=new ProductionPilotReadSession({batchId:randomUUID(),manifestSha256,now:()=>now,maxAgeMs:1000});
const load=vi.fn(async()=>({observedAt:new Date(now).toISOString(),file:'/private/original.json',result:{kind:'success' as const,requestId:'original-read',envelope:{},response:{brand_list:[{brand_id:42}]}}}));return{session,load,advance:(ms:number)=>{now+=ms;}};}
it('reuses exact metadata evidence without refreshing its observed time or losing its original file',async()=>{const f=fixture();const original=await f.session.read(scope,'/api/v2/product/get_brand_list',{category_id:'1',offset:'0'},f.load);f.advance(900);const cached=await f.session.read(scope,'/api/v2/product/get_brand_list',{offset:'0',category_id:'1'},f.load);expect(f.load).toHaveBeenCalledTimes(1);expect(cached).toEqual({...original,cacheHit:true});expect(cached.observedAt).toBe('2026-09-15T10:00:00.000Z');if(cached.result.kind!=='success')throw Error('Expected fixture success');(cached.result.response.brand_list as any)[0].brand_id=99;const again=await f.session.read(scope,'/api/v2/product/get_brand_list',{offset:'0',category_id:'1'},f.load);if(again.result.kind!=='success')throw Error('Expected fixture success');expect((again.result.response.brand_list as any)[0].brand_id).toBe(42);});
it.each(['connection','category','language','cursor'])('does not share a cached response across changed %s',async key=>{const f=fixture();const query={category_id:'1',offset:'0',language:'vi'};await f.session.read(scope,'/api/v2/product/get_brand_list',query,f.load);await f.session.read(key==='connection'?{...scope,connectionRevision:2}:scope,'/api/v2/product/get_brand_list',{...query,...(key==='category'?{category_id:'2'}:key==='language'?{language:'en'}:key==='cursor'?{offset:'20'}:{})},f.load);expect(f.load).toHaveBeenCalledTimes(2);});
it('expires cache using original observation time',async()=>{const f=fixture();await f.session.read(scope,'/api/v2/product/get_category',{},f.load);f.advance(1001);await f.session.read(scope,'/api/v2/product/get_category',{},f.load);expect(f.load).toHaveBeenCalledTimes(2);});
it.each(['product/get_item_limit','product/get_item_list','product/get_model_list','product/get_item_base_info','shop/get_shop_info','shop/get_warehouse_detail'])('always refreshes volatile or write-critical %s',async path=>{const f=fixture();await f.session.read(scope,'/api/v2/'+path,{},f.load);await f.session.read(scope,'/api/v2/'+path,{},f.load);expect(f.load).toHaveBeenCalledTimes(2);});
it('coalesces simultaneous identical metadata misses',async()=>{const f=fixture();await Promise.all([f.session.read(scope,'/api/v2/product/get_category',{},f.load),f.session.read(scope,'/api/v2/product/get_category',{},f.load)]);expect(f.load).toHaveBeenCalledTimes(1);});
it('does not cache denied or unknown responses',async()=>{const f=fixture();f.load.mockResolvedValue({observedAt:'2026-09-15T10:00:00.000Z',file:'/private/denial.json',result:{kind:'rejected',code:'error_api_permission'}} as any);await f.session.read(scope,'/api/v2/product/get_category',{},f.load);await f.session.read(scope,'/api/v2/product/get_category',{},f.load);expect(f.load).toHaveBeenCalledTimes(2);});
it('rejects another source manifest and auth query fields before any loader call',async()=>{const f=fixture();expect(()=>f.session.assertManifest(manifestSha256)).not.toThrow();expect(()=>f.session.assertManifest('b'.repeat(64))).toThrow();await expect(f.session.read(scope,'/api/v2/product/get_category',{access_token:'never-copy'},f.load)).rejects.toThrow();expect(f.load).not.toHaveBeenCalled();});
